onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_flex_ctr/DUT/rollover_val
add wave -noupdate /tb_flex_ctr/DUT/count_out
add wave -noupdate /tb_flex_ctr/DUT/clk
add wave -noupdate /tb_flex_ctr/DUT/n_rst
add wave -noupdate /tb_flex_ctr/DUT/clear
add wave -noupdate /tb_flex_ctr/DUT/count_enable
add wave -noupdate /tb_flex_ctr/DUT/rollover_flag
add wave -noupdate /tb_flex_ctr/DUT/N16
add wave -noupdate /tb_flex_ctr/DUT/N17
add wave -noupdate /tb_flex_ctr/DUT/N18
add wave -noupdate /tb_flex_ctr/DUT/N19
add wave -noupdate /tb_flex_ctr/DUT/N20
add wave -noupdate /tb_flex_ctr/DUT/N21
add wave -noupdate /tb_flex_ctr/DUT/N22
add wave -noupdate /tb_flex_ctr/DUT/N23
add wave -noupdate /tb_flex_ctr/DUT/N27
add wave -noupdate /tb_flex_ctr/DUT/N28
add wave -noupdate /tb_flex_ctr/DUT/N29
add wave -noupdate /tb_flex_ctr/DUT/N30
add wave -noupdate /tb_flex_ctr/DUT/N31
add wave -noupdate /tb_flex_ctr/DUT/N32
add wave -noupdate /tb_flex_ctr/DUT/N33
add wave -noupdate /tb_flex_ctr/DUT/N34
add wave -noupdate /tb_flex_ctr/DUT/n56
add wave -noupdate /tb_flex_ctr/DUT/n57
add wave -noupdate /tb_flex_ctr/DUT/n58
add wave -noupdate /tb_flex_ctr/DUT/n59
add wave -noupdate /tb_flex_ctr/DUT/n60
add wave -noupdate /tb_flex_ctr/DUT/n61
add wave -noupdate /tb_flex_ctr/DUT/n62
add wave -noupdate /tb_flex_ctr/DUT/n63
add wave -noupdate /tb_flex_ctr/DUT/n64
add wave -noupdate /tb_flex_ctr/DUT/n65
add wave -noupdate /tb_flex_ctr/DUT/n66
add wave -noupdate /tb_flex_ctr/DUT/n67
add wave -noupdate /tb_flex_ctr/DUT/n68
add wave -noupdate /tb_flex_ctr/DUT/n69
add wave -noupdate /tb_flex_ctr/DUT/n70
add wave -noupdate /tb_flex_ctr/DUT/n71
add wave -noupdate /tb_flex_ctr/DUT/n72
add wave -noupdate /tb_flex_ctr/DUT/n73
add wave -noupdate /tb_flex_ctr/DUT/n74
add wave -noupdate /tb_flex_ctr/DUT/n75
add wave -noupdate /tb_flex_ctr/DUT/n76
add wave -noupdate /tb_flex_ctr/DUT/n77
add wave -noupdate /tb_flex_ctr/DUT/n78
add wave -noupdate /tb_flex_ctr/DUT/n79
add wave -noupdate /tb_flex_ctr/DUT/n80
add wave -noupdate /tb_flex_ctr/DUT/n81
add wave -noupdate /tb_flex_ctr/DUT/n82
add wave -noupdate /tb_flex_ctr/DUT/n83
add wave -noupdate /tb_flex_ctr/DUT/n84
add wave -noupdate /tb_flex_ctr/DUT/n85
add wave -noupdate /tb_flex_ctr/DUT/n86
add wave -noupdate /tb_flex_ctr/DUT/n87
add wave -noupdate /tb_flex_ctr/DUT/n88
add wave -noupdate /tb_flex_ctr/DUT/n89
add wave -noupdate /tb_flex_ctr/DUT/n90
add wave -noupdate /tb_flex_ctr/DUT/n91
add wave -noupdate /tb_flex_ctr/DUT/n92
add wave -noupdate /tb_flex_ctr/DUT/n93
add wave -noupdate /tb_flex_ctr/DUT/n94
add wave -noupdate /tb_flex_ctr/DUT/n95
add wave -noupdate /tb_flex_ctr/DUT/n96
add wave -noupdate /tb_flex_ctr/DUT/n97
add wave -noupdate /tb_flex_ctr/DUT/n98
add wave -noupdate /tb_flex_ctr/DUT/n99
add wave -noupdate /tb_flex_ctr/DUT/n100
add wave -noupdate /tb_flex_ctr/DUT/n101
add wave -noupdate /tb_flex_ctr/DUT/n102
add wave -noupdate /tb_flex_ctr/DUT/n103
add wave -noupdate /tb_flex_ctr/DUT/n104
add wave -noupdate /tb_flex_ctr/DUT/n105
add wave -noupdate /tb_flex_ctr/DUT/n106
add wave -noupdate /tb_flex_ctr/DUT/n107
add wave -noupdate /tb_flex_ctr/DUT/n108
add wave -noupdate /tb_flex_ctr/DUT/n109
add wave -noupdate /tb_flex_ctr/DUT/n110
add wave -noupdate /tb_flex_ctr/DUT/n111
add wave -noupdate /tb_flex_ctr/DUT/n112
add wave -noupdate /tb_flex_ctr/DUT/n113
add wave -noupdate /tb_flex_ctr/DUT/n114
add wave -noupdate /tb_flex_ctr/DUT/n115
add wave -noupdate /tb_flex_ctr/DUT/n116
add wave -noupdate /tb_flex_ctr/DUT/n117
add wave -noupdate /tb_flex_ctr/DUT/n118
add wave -noupdate /tb_flex_ctr/DUT/n119
add wave -noupdate /tb_flex_ctr/DUT/n120
add wave -noupdate /tb_flex_ctr/DUT/n121
add wave -noupdate /tb_flex_ctr/DUT/n122
add wave -noupdate /tb_flex_ctr/DUT/n123
add wave -noupdate /tb_flex_ctr/DUT/n124
add wave -noupdate /tb_flex_ctr/DUT/n125
add wave -noupdate /tb_flex_ctr/DUT/n126
add wave -noupdate /tb_flex_ctr/DUT/n127
add wave -noupdate /tb_flex_ctr/DUT/n128
add wave -noupdate /tb_flex_ctr/DUT/n129
add wave -noupdate /tb_flex_ctr/DUT/n130
add wave -noupdate /tb_flex_ctr/DUT/n131
add wave -noupdate /tb_flex_ctr/DUT/n132
add wave -noupdate /tb_flex_ctr/DUT/n133
add wave -noupdate /tb_flex_ctr/DUT/n134
add wave -noupdate /tb_flex_ctr/DUT/n135
add wave -noupdate /tb_flex_ctr/DUT/n136
add wave -noupdate /tb_flex_ctr/DUT/n137
add wave -noupdate /tb_flex_ctr/DUT/n138
add wave -noupdate /tb_flex_ctr/DUT/n139
add wave -noupdate /tb_flex_ctr/DUT/n140
add wave -noupdate /tb_flex_ctr/DUT/n141
add wave -noupdate /tb_flex_ctr/DUT/n142
add wave -noupdate /tb_flex_ctr/DUT/n143
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {515028 ps} {530789 ps}
